name: Build Release

on:
  workflow_dispatch:
  push:
    branches:
      - main
    tags:
      - '**'

env:
  packageName: "nadena.dev.ndmf.reactive-query"


jobs:
  build-release:
    uses: nadena-dev/nadenadev-ci/.github/workflows/build-release.yml@main
    with:
      packageName: "nadena.dev.ndmf.reactive-query"
      test_assembly: nadena.dev.ndmf.reactive-query.tests,nadena.dev.ndmf.reactive-query.tests.editor
    secrets:
      UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
    permissions:
      contents: write
      checks: write